#!/bin/bash -x

exec &> >(tee -a /var/log/refresh_index.log)

. /refresh_index.envs
export $(cut -d' ' -f3 /refresh_index.envs | cut -d= -f1)

printenv

flask base_uri list

# Build the index of the data on the URI
flask base_uri index smb://test-share
flask base_uri index s3://test-bucket
exit 0
