#!/bin/bash -x
set -euxo pipefail

# get environment variables from Docker-style env_file in properly escaped shell syntax:
declare -p | grep -E "$(cut -d= -f1 /refresh_index.envs.reference | xargs echo -n | tr ' ' '|')" > /refresh_index.envs

cd /app

# Note: init, upgrade and migrate can fail
cat $JWT_PUBLIC_KEY_FILE

# Initialization
flask db init

supervisord
