#!/bin/bash -x

exec &> >(tee -a /var/log/refresh_index.log)

. /refresh_index.envs
export $(cut -d' ' -f3 /refresh_index.envs | cut -d= -f1)

printenv

flask base_uri list

# Build the index of the data on the URI
DSERVER_BASE_URI_FILE="${DSERVER_BASE_URI_FILE:-/app/base_uris}"

for base_uri in $(cat "${DSERVER_BASE_URI_FILE}"); do
  flask base_uri index "${base_uri}"
done

exit 0
