name: dtool-lookup-server-container-image-build-and-test

on: [push, pull_request]

jobs:
  build-and-test:
    uses: jotelha/dtool-framework-workflows/.github/workflows/dtool-lookup-framewok-generic-container-image-build-and-test.yml@master
    with:
      image: jotelha/dtool-lookup-server
      service: dtool_lookup_server
      docker_file: ./compose/production/dtool_lookup_server/Dockerfile
