name: dserver-container-image-build-and-test

on:
  push:
    branches:
      - master
  pull_request:

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pip-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pip-tools and pipdeptree
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install pip-tools
          pip install pipdeptree
          pip install setuptools_scm
          
      - name: Requirements inspection and upgrade
        run: |
          cd compose/production/dserver
          echo "### Initial pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Initial pipdeptree ###"
          pipdeptree | tee pipdeptree.initial
          echo "### pip-compile --upgrade ###"
          pip-compile --upgrade requirements.in
          echo "### requirements.txt diff ###"
          git diff requirements.txt | tee diff_requirements.txt
          echo "### Repeated pip install -r requirements.txt ###"
          pip install -r requirements.txt
          echo "### Upgraded pipdeptree ###"
          pipdeptree | tee pipdeptree.upgraded

  build-and-test:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dtool-lookup-framework-generic-container-image-build-and-test.yml@master
    with:
      image: jotelha/dserver
      service: dserver
      docker_file: ./compose/production/dserver/Dockerfile
