name: publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish:
    uses: livMatS/dtool-framework-workflows/.github/workflows/dtool-lookup-framewok-generic-container-image-publication.yml@master
    with:
      image: jotelha/dtool-lookup-server
      docker_file: ./compose/production/dtool_lookup_server/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
